name: 'Nebula Cherry Pick Robot'
author: rivery.wang
description: 'Create pr to target branch when this pr has special label'
inputs:
  from_repo:
    description: 'from repository to current'
    required: true
  repo_token:
    description: 'repository token to access the codebase'
    required: true
  pr_label:
    description: 'which label to auto create pr'
    required: true
runs:
  using: "node16"
  main: 'dist/index.js'

branding:
  icon: 'refresh-cw'
  color: 'yellow'